version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://34.87.91.112:8000
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=stepcare_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bunnyz2710
      - DJANGO_SETTINGS_MODULE=studforce.settings
    volumes:
      - ./Backend:/app
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: db
    image: postgres:13
    environment:
      - POSTGRES_DB=stepcare_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bunnyz2710
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
